create table if not exists public.sales_orders (
  id bigint generated by default as identity primary key,
  receipt_number text not null unique,
  business_name text,
  business_phone text,
  customer_name text not null,
  customer_phone text not null,
  google_review_link text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  discount numeric(12, 2) not null default 0,
  tax numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  created_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sales_orders_updated_at_idx
  on public.sales_orders (updated_at desc);

alter table public.sales_orders
  add column if not exists payment_mode text not null default 'online',
  add column if not exists payment_status text not null default 'unpaid',
  add column if not exists payment_detected_at timestamptz,
  add column if not exists payment_confirmed_at timestamptz,
  add column if not exists payment_reference text,
  add column if not exists payment_source text,
  add column if not exists payment_match_note text,
  add column if not exists payment_sms_id text;

create index if not exists sales_orders_payment_status_idx
  on public.sales_orders (payment_status);

create table if not exists public.supplier_records (
  id bigint generated by default as identity primary key,
  supplier_name text not null,
  item_details text,
  total_amount numeric(12, 2) not null default 0,
  paid_amount numeric(12, 2) not null default 0,
  due_amount numeric(12, 2) not null default 0,
  payment_status text not null default 'due',
  transaction_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists supplier_records_transaction_date_idx
  on public.supplier_records (transaction_date desc);

create table if not exists public.scheduled_review_messages (
  id text primary key,
  receipt_number text not null,
  customer_name text not null,
  customer_phone text not null,
  business_name text,
  business_phone text,
  google_review_link text not null,
  scheduled_at timestamptz not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scheduled_review_messages_due_idx
  on public.scheduled_review_messages (status, scheduled_at);

create table if not exists public.incoming_payment_sms (
  id text primary key,
  message_id text,
  sender text,
  recipient text,
  received_at timestamptz,
  message text not null,
  parsed jsonb not null default '{}'::jsonb,
  match_status text not null default 'ignored',
  matched_receipt_number text,
  created_at timestamptz not null default now()
);

create index if not exists incoming_payment_sms_created_at_idx
  on public.incoming_payment_sms (created_at desc);

create table if not exists public.gmail_oauth_tokens (
  id text primary key,
  email text,
  refresh_token text not null,
  access_token text,
  expires_at timestamptz,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.processed_gmail_messages (
  message_id text primary key,
  processed_at timestamptz not null default now()
);

create table if not exists public.incoming_payment_emails (
  id text primary key,
  sender text,
  subject text,
  received_at timestamptz,
  message text not null,
  parsed jsonb not null default '{}'::jsonb,
  match_status text not null default 'ignored',
  matched_receipt_number text,
  created_at timestamptz not null default now()
);

create index if not exists incoming_payment_emails_created_at_idx
  on public.incoming_payment_emails (created_at desc);
