create table if not exists public.sales_orders (
  id bigint generated by default as identity primary key,
  receipt_number text not null unique,
  business_name text,
  business_phone text,
  customer_name text not null,
  customer_phone text not null,
  google_review_link text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  discount numeric(12, 2) not null default 0,
  tax numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  created_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sales_orders_updated_at_idx
  on public.sales_orders (updated_at desc);

create table if not exists public.supplier_records (
  id bigint generated by default as identity primary key,
  supplier_name text not null,
  item_details text,
  total_amount numeric(12, 2) not null default 0,
  paid_amount numeric(12, 2) not null default 0,
  due_amount numeric(12, 2) not null default 0,
  payment_status text not null default 'due',
  transaction_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists supplier_records_transaction_date_idx
  on public.supplier_records (transaction_date desc);
